cadastros/urls.py
from django.urls import path

from .views import AvaliacaoCreate, AvaliacaoDelete, AvaliacaoList, AvaliacaoUpdate, CampoCreate, AtividadeCreate
from .views import CampoUpdate, AtividadeUpdate
from .views import CampoDelete, AtividadeDelete
from .views import CampoList, AtividadeList


urlpatterns = [
    path('cadastrar/campo/', CampoCreate.as_view(), name='cadastrar-campo'),
    path('cadastrar/atividade/', AtividadeCreate.as_view(), name='cadastrar-atividade'),
    path('cadastrar/avaliacao/', AvaliacaoCreate.as_view(), name='cadastrar-avaliacao'),
    
    path('editar/campo/<int:pk>/', CampoUpdate.as_view(), name='editar-campo'),
    path('editar/atividade/<int:pk>', AtividadeUpdate.as_view(), name='editar-atividade'),
    path('editar/avaliacao/<int:pk>', AvaliacaoUpdate.as_view(), name='editar-avaliacao'),
    
    path('deletar/campo/<int:pk>/', CampoDelete.as_view(), name='deletar-campo'),
    path('deletar/atividade/<int:pk>/', AtividadeDelete.as_view(), name='deletar-atividade'),
    path('deletar/avaliacao/<int:pk>/', AvaliacaoDelete.as_view(), name='deletar-avaliacao'),
    
    path('listar/campos/', CampoList.as_view(), name='listar-campos'),
    path('listar/atividades/', AtividadeList.as_view(), name='listar-atividades'),
    path('listar/avaliacoes/', AvaliacaoList.as_view(), name='listar-avaliacoes'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Campo(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=150, verbose_name="Descrição")
    
    def __str__(self) -> str:
        return f"{self.nome} - {self.descricao}"
    
class Atividade(models.Model):
    numero = models.IntegerField(verbose_name="Número")
    descricao = models.CharField(max_length=150, verbose_name="Descricão")
    pontos = models.DecimalField(decimal_places=1, max_digits=4)
    detalhes = models.CharField(max_length=100)
    
    campo = models.ForeignKey(Campo, on_delete=models.PROTECT)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return f"{self.numero} - {self.descricao} ({self.campo.nome})"
    
class Avaliacao(models.Model):
    atividade = models.ForeignKey(Atividade, on_delete=models.PROTECT)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    
    arquivo = models.FileField(upload_to='pdf/')
    
    def __str__(self) -> str:
        return f'[{self.pk}] {self.usuario} - {self.atividade}/{self.atividade.campo}'
    
    class Meta:
        verbose_name_plural = "Avaliações"
        verbose_name = "Avaliação"
    

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Perfil(models.Model):
    nome_completo = models.CharField(max_length=50, null=True)
    cpf = models.CharField(max_length=14, null=True, verbose_name="CPF")
    telefone = models.CharField(max_length=16, null=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = "Perfis"
        
    def __str__(self) -> str:
        return str(self.usuario)
        

cadastros/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin

from django.shortcuts import get_object_or_404

from .models import Avaliacao, Campo, Atividade


# Create your views here.
class CampoCreate(GroupRequiredMixin, CreateView):
    model = Campo
    fields = ['nome', 'descricao']
    template_name = 'form.html'
    success_url = reverse_lazy('listar-campos')
    login_url = reverse_lazy('nao-autenticado')
    group_required = u"Reitor"
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Cadastro de campos"
        
        return context

class AtividadeCreate(LoginRequiredMixin, CreateView):
    model = Atividade
    fields = ['numero', 'descricao', 'pontos', 'detalhes', 'campo']
    template_name = 'form.html'
    success_url = reverse_lazy('listar-atividades')
    login_url = reverse_lazy('login')
    
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        
        return super().form_valid(form)
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Cadastro de atividades"
        
        return context
    
class AvaliacaoCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Avaliacao
    fields = ['atividade', 'arquivo']
    template_name = 'form.html'
    success_url = reverse_lazy('listar-avaliacoes')
        
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        
        return super().form_valid(form)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['atividade'].queryset = Atividade.objects.filter(usuario=self.request.user)
        
        return form
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Cadastro de avaliações"
        context['upload'] = "multipart/form-data"
        
        return context
    
class CampoUpdate(GroupRequiredMixin, UpdateView):
    model = Campo
    fields = ['nome', 'descricao']
    template_name = 'form.html'
    success_url = reverse_lazy('listar-campos')
    login_url = reverse_lazy('nao-autenticado')
    group_required = [u"Reitor", u"Grupo2"]
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Editar Campo"
        context['botao'] = "Salvar"
        
        return context
    
class AtividadeUpdate(LoginRequiredMixin, UpdateView):
    model = Atividade
    fields = ['numero', 'descricao', 'pontos', 'detalhes', 'campo']
    template_name = 'form.html'
    success_url = reverse_lazy('listar-atividades')
    login_url = reverse_lazy('login')
    
    def get_object(self, queryset=None):
        self.object = get_object_or_404(Atividade, pk=self.kwargs['pk'], usuario=self.request.user)
        
        return self.object
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Editar Atividade"
        context['botao'] = "Salvar"
        
        return context
    
class AvaliacaoUpdate(GroupRequiredMixin, UpdateView):
    model = Avaliacao
    fields = ['atividade', 'arquivo']
    template_name = 'form.html'
    success_url = reverse_lazy('listar-avaliacoes')
    login_url = reverse_lazy('nao-autenticado')
    group_required = u"Reitor"
    
    def get_object(self, queryset=None):
        self.object = get_object_or_404(Avaliacao, pk=self.kwargs['pk'])
        
        return self.object
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        atividade = Atividade.objects.get(pk=self.kwargs['pk'])
        form.fields['atividade'].queryset = Atividade.objects.filter(usuario=atividade.usuario)
        
        return form
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Editar Avaliação"
        context['botao'] = "Salvar"
        context['upload'] = "multipart/form-data"
        
        return context
    
class CampoDelete(GroupRequiredMixin, DeleteView):
    model = Campo
    template_name = 'form.html'
    success_url = reverse_lazy('listar-campos')
    login_url = reverse_lazy('nao-autenticado')
    group_required = u"Reitor"
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Excluir campo"
        context['subtitulo'] = "Confirme para excluir o campo definitivamente"
        context['botao'] = "Excluir"
        context['estilo_botao'] = "btn-danger"
        context['tag_exclusao'] = True
        
        return context
    
class AtividadeDelete(LoginRequiredMixin, DeleteView):
    model = Atividade
    template_name = 'form.html'
    success_url = reverse_lazy('listar-atividades')
    login_url = reverse_lazy('login')
    
    def get_object(self, queryset=None):
        self.object = get_object_or_404(Atividade, pk=self.kwargs['pk'], usuario=self.request.user)
        
        return self.object
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Excluir atividade"
        context['subtitulo'] = "Confirme para excluir a atividade definitivamente"
        context['botao'] = "Excluir"
        context['estilo_botao'] = "btn-danger"
        context['tag_exclusao'] = True
        
        return context
    
class AvaliacaoDelete(GroupRequiredMixin, DeleteView):
    model = Avaliacao
    template_name = 'form.html'
    success_url = reverse_lazy('listar-avaliacoes')
    login_url = reverse_lazy('nao-autenticado')
    group_required = u"Reitor"
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        context['titulo'] = "Excluir avaliação"
        context['subtitulo'] = "Confirme para excluir a avaliação definitivamente"
        context['botao'] = "Excluir"
        context['estilo_botao'] = "btn-danger"
        context['tag_exclusao'] = True
        
        return context
    
class CampoList(LoginRequiredMixin, ListView):
    model = Campo
    template_name = 'campo.html'
    login_url = reverse_lazy('nao-autenticado')
    
class AtividadeList(LoginRequiredMixin, ListView):
    model = Atividade
    template_name = 'atividade.html'
    login_url = reverse_lazy('login')
    # paginate_by = 1 # Limita o numero de registros exibidos na tela, dentro do HTML tem a paginação e validação. É mais rápido que o DataTable se tiver uma quantidade de registros gigantesca
    
    def get_queryset(self):
        # Desabilitado pois já estou utilizando DataTable, o codigo comentado filtra as paginas de acordo com a pesquisa do usuario
        # input_usuario = self.request.GET.get('detalhes')
        # if input_usuario:
        #     self.object_list = Atividade.objects.filter(Q(usuario=self.request.user) & Q(detalhes__icontains=input_usuario))
        # else:
        #     self.object_list = Atividade.objects.filter(usuario=self.request.user)
            
        self.object_list = Atividade.objects.filter(usuario=self.request.user)
        
        return self.object_list

class AvaliacaoList(LoginRequiredMixin, ListView):
    model = Avaliacao
    template_name = 'avaliacao.html'
    login_url = reverse_lazy('nao-autenticado')
    
    def get_queryset(self, queryset=None):
        self.object_list = Avaliacao.objects.filter(usuario=self.request.user)
        
        if self.request.user.groups.filter(name='Reitor').exists():
            self.object_list = Avaliacao.objects.all()
        
        return self.object_list

cadastros/templates/atividade.html
{% extends 'base.html' %}

{% block title %}
<title>Atividades</title>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between">
    <h3>
        Lista das suas atividades registradas
    </h3>
    <a href="{% url 'cadastrar-atividade' %}" class="btn btn-primary float-end">Adicionar atividade</a>
</div>
<hr>

<!-- Paginação caso o paginate_by na AtividadeList estiver ativo -->
<!-- Está desativado pois estou utilizando o DataTable -->
<!-- <form action="?" method="GET">
    <input type="text" name="detalhes" id="" value="{{ request.GET.detalhes }}" class="p-1 border" autocomplete="off">
    <button type="submit" class="btn btn-primary">Buscar</button>
    <a href="{% url 'listar-atividades' %}" class="btn btn-secondary">Limpar</a>
</form> -->

<div class="table-responsive">
    <table class="table table-striped" id="tabelaAtividades">
        <thead>
            <tr>
                <th>Número</th>
                <th>Descrição</th>
                <th>Pontos</th>
                <th>Detalhes</th>
                <th>Campo</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for atividade in object_list %}
            <tr>
                <td>{{ atividade.numero }}</td>
                <td>{{ atividade.descricao }}</td>
                <td>{{ atividade.pontos }}</td>
                <td>{{ atividade.detalhes }}</td>
                <td>{{ atividade.campo }}</td>
                <td>
                    <a href="{% url 'editar-atividade' atividade.pk %}" class="btn btn-warning btn-sm" title="Editar">Editar</a>
                    <a href="{% url 'deletar-atividade' atividade.pk %}" class="btn btn-danger btn-sm" title="Excluir">Excluir</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Nenhuma atividade registrada.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Paginação caso o paginate_by na AtividadeList estiver ativo -->
    <!-- Está desativado pois estou utilizando o DataTable -->
    <!-- <div class="text-center">
        {% if page_obj.has_previous %} 
        {% if request.GET.detalhes %}
        <a href="?page={{ page_obj.previous_page_number }}&detalhes={{ request.GET.detalhes }}" class="btn btn-primary">Voltar</a>
        {% else %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">Voltar</a>
        {% endif %}
        {% else %}
        <a class="btn btn-primary disabled">Voltar</a>
        {% endif %}

        <span>Página {{ page_obj.number }} de {{ page_obj.paginator.count}}</span>

        {% if page_obj.has_next %}
        {% if request.GET.detalhes %}
        <a href="?page={{ page_obj.next_page_number }}&detalhes={{ request.GET.detalhes }}" class="btn btn-primary">Próximo</a>
        {% else %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">Próximo</a>
        {% endif %}
        {% else %}
        <a class="btn btn-primary disabled">Próximo</a>
        {% endif %}
    </div> -->
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function() {
        window.alert = function(){} // Recurso tecnico para corrigir bug do DataTable
        $("#tabelaAtividades").DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
            }
        })
    })

</script>
{% endblock %}

cadastros/templates/avaliacao.html
{% extends 'base.html' %}

{% block title %}
<title>avaliacaos</title>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between">
    <h3>
        Lista de avaliações registradas
    </h3>
    <a href="{% url 'cadastrar-avaliacao' %}" class="btn btn-primary">Cadastrar avaliação</a>
</div>
<hr>
<p class="lead">
    Registros de avaliações que serão/foram feitas presencialmente
</p>
<div class="table-responsive">
    <table class="table table-striped" id="tabelaAvaliacoes">
        <thead>
            <tr>
                <th>Professor</th>
                <th>Avaliação</th>
                <th>Atividade</th>
                <th>Campo</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for avaliacao in object_list %}
            <tr>
                <td>{{ avaliacao.usuario }}</td>
                <td><a href="{{ avaliacao.arquivo.url }}">Ver</a></td>
                <td>{{ avaliacao.atividade.descricao }}</td>
                <td>{{ avaliacao.atividade.campo.descricao }}</td>
                <td>
                    <a href="{% url 'editar-avaliacao' avaliacao.pk %}" class="btn btn-warning btn-sm" title="Editar">Editar</a>
                    <a href="{% url 'deletar-avaliacao' avaliacao.pk %}" class="btn btn-danger btn-sm" title="Excluir">Excluir</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">Nenhuma avaliação registrada.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function() {
        window.alert = function(){} // Recurso tecnico para corrigir bug do DataTable
        $("#tabelaAvaliacoes").DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
            }
        })
    })
</script>
{% endblock %}

cadastros/templates/campo.html
{% extends 'base.html' %}

{% block title %}
<title>Campos</title>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between">
    <h3>
        Lista de campos registrados
    </h3>
    <a href="{% url 'cadastrar-campo' %}" class="btn btn-primary">Cadastrar campo</a>
</div>
<hr>
<div class="table-responsive">
    <table class="table table-striped" id="tabelaCampo">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for campo in object_list %}
            <tr>
                <td>{{ campo.nome }}</td>
                <td>{{ campo.descricao }}</td>
                <td>
                    <a href="{% url 'editar-campo' campo.pk %}" class="btn btn-warning btn-sm" title="Editar">Editar</a>
                    <a href="{% url 'deletar-campo' campo.pk %}" class="btn btn-danger btn-sm" title="Excluir">Excluir</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Nenhum campo registrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function(event) {
        window.alert = function(){} // Recurso tecnico para corrigir bug do DataTable
        $("#tabelaCampo").DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
            }
        })
    })
</script>
{% endblock %}

cadastros/templates/form.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<h3>{{ titulo }}</h3>
<p class="lead">
    {% if subtitulo %}
    {{ subtitulo }}
    {% else %}
    Preencha todos os campos obrigatorios
    {% endif %}
</p>
<hr>
<form action="" method="post" enctype={{ upload }}>
    {% csrf_token %}

    {{ form|crispy }}

    {% if tag_exclusao %}
    <p>Deseja excluir o registro: <strong>{{ object }}</strong>?</p>
    {% endif %}

    <button type="submit" class="btn btn-primary {{ estilo_botao }}">
        {% autoescape off %}
        <!-- Transforma a {{ variavel }} de string para html -->
        {% endautoescape %}
        {% if botao %}
        {{ botao }}
        {% else %}
        Cadastrar
        {% endif %}
    </button>

</form>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function() {
        $('#id_cpf').mask("000.000.000-00")
        // $('#id_telefone').mask("(00) 0 0000-0000")

        var mascaraTelefone = function(val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009'
        }, 
            opcoes = {
                onKeyPress: function(val, e, field, options) {
                    field.mask(mascaraTelefone.apply({}, arguments), options)
                }
            }

        $('#id_telefone').mask(mascaraTelefone, opcoes)
    })
</script>
{% endblock %}